### PR TITLE
V2- Refactor Cloud Backup API docs

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
Fixes #87

**Comment by rackernexus** [comment]
HULK PREVIEW

* [`api-docs/cloud-backup-v1`](https://staging.developer.rackspace.com/build-ed3bef40d5/docs/cloud-backup/v1/)
* The content at `internal-api-docs/cloud-backup-v2` is not mapped anywhere!
* [`api-docs/cloud-backup-v2`](https://staging.developer.rackspace.com/build-ed3bef40d5/docs/cloud-backup/v2/developer-guide/)


Your build succeeded, but some of your content is not mapped anywhere in the control repository yet! See the [Deconst documentation](https://deconst.horse/writing-docs/coordinator/mapping/) for information about content mapping.

**Comment by cyrichardson** [comment]
Fixes #87

**Comment by cyrichardson** [comment]
Closes #87

**Pull request merged**
